const tags: string[] = [
  'Shop',
  'Parking',
  // 'Hotel Parking',
  // 'Free Hotel Wi-Fi',
  'Bus Stop',
  // 'Free Hotel Parking',
  // 'Non-smoking Rooms',
  'Non-smoking throughout',
  'Village',
  'Air Conditioning',
  'Public Transport',
  'Apartment',
  // 'Stop',
  'Family Rooms',
  'Hotel with Garden',
  'Locality',
  'Sports Field',
  'Bus',
  'Pets Allowed',
  'Place of Worship',
  'Restaurant',
  'School',
  'Surface Parking',
  // 'Christian',
  'Hotel Pool',
  'Hotel',
  'Wheelchair Accessible',
  'Outdoor Hotel Pool',
  '24-Hour Front Desk',
  'Airport Shuttle',
  'Holiday Home',
  // 'Hotel Laundry',
  'Design Hotel',
  'Tourist Information',
  // 'Hotel Restaurant',
  'Shelter',
  'Countryside Hotel',
  'Playground',
  // 'Convenience Store',
  'Hotel Bar',
  'Park',
  // 'Cemetery',
  // 'Gas Station',
  'Room Service',
  'Peak',
  'Café',
  'Supermarket',
  'Soccer',
  // 'Office',
  'Hotel Near Golf Course',
  'Fast Food',
  'Swimming Pool',
  // 'Hotel Tennis Court',
  'Pier',
  // 'Free',
  'Seaside Hotel',
  'Bank',
  // 'Hotel with Facilities for Disabled Guests',
  'Tennis',
  'Beachfront Hotel',
  // 'Hotel Fitness',
  // 'Hotel Playground',
  // 'Free Parking',
  'Isolated Dwelling',
  'Shared Kitchen',
  'Public Toilets',
  'Guidepost',
  'Pharmacy',
  'Post Box',
  'Church',
  // 'Hotel Dry Cleaning',
  'Sports Center',
  // 'Hotel Sauna',
  'Clothes Shop',
  'ATM',
  'Guest House',
  'Kindergarten',
  'Customers Only',
  // 'Accessible',
  'Asphalt',
  'Drinking Water',
  'Open 24/7',
  'Bridal Suite',
  'District',
  // 'Hotel Concierge',
  'Hairdresser',
  // 'Family Friendly Hotel',
  'Catholic',
  'Wi-Fi',
  'Villa',
  'Eco-Friendly Hotel',
  // 'Guest Accommodation',
  'Muslim',
  'Hospital',
  'Luxury Hotel',
  'Bar',
  'Memorial',
  'Games Room',
  'Bakery',
  // 'Bus Station',
  'Post Office',
  'Pub',
  'Car Repair',
  // 'Allergy-free Rooms',
  'View Point',
  // 'Hotel Spa / Wellness',
  'Tourist Information Board',
  'Basketball',
  'Bed and Breakfast',
  // 'Hotel Bowling',
  'Takeaway',
  'Beach',
  'Police',
  'Train Station',
  'Government Office',
  'Heritage',
  'Camp Site',
  'Company Office',
  'Baseball',
  'Artwork',
  'Ruins',
  'Picnic Site',
  'Town Hall',
  'Fountain',
  'Suburb',
  'Island',
  'Golf',
  'Fire Station',
  'University',
  'Car Dealership',
  'Doctor',
  'Craft',
  // 'Hotel Mini Golf',
  'Nature Reserve',
  'Hostel',
  'Lake',
  'Town',
  'Home Stay',
  'Picnic Table',
  'Clinic',
  'Pizza',
  // 'Hotel Solarium',
  'Train Stop',
  // 'Paid Parking',
  'Hotel Charging Station',
  'Community Centre',
  'Museum',
  'Regional Cuisine',
  'Outdoor Seating',
  'Farm',
  // 'Adult Only Hotel',
  'Library',
  'Indoor Hotel Pool',
  // 'Free Wi-Fi',
  'Roman Catholic',
  'Burgers',
  'Private Hotel Beach',
  'Social Facility',
  'Kiosk',
  'Swimming',
  'Track',
  'Butcher',
  'Chalet',
  'Rest Area',
  // 'Dentist',
  'Car Wash',
  // 'Beauty Salon',
  'Grass',
  // 'Diesel',
  'Monument',
  'Gourmet Hotel',
  'Dam',
  'Hardware',
  'Motel',
  'Electronics Shop',
  // 'Free Internet Access',
  'College',
  'Station',
  'Furniture Shop',
  'Tourist Information Map',
  'Market',
  // 'Aparthotel',
  'Bridge',
  'Sand',
  'Mobile Phone Shop',
  'Florist',
  'Tower',
  'Shopping Mall',
  'Chapel',
  // 'Octane 95',
  'Shoes Shop',
  'Italian Cuisine',
  'Archaeological Site',
  'Spring',
  'Alcohol Shop',
  'Do It Yourself',
  // 'Waste Water Plant',
  'Buddhist',
  'Christian Cemetery',
  'Outdoor',
  'Airport',
  'Car Parts Shop',
  'Tram Stop',
  'Regional Heritage',
  'Hotel Hammam',
  'Stadium',
  'Castle',
  'Factory',
  'Pond',
  'Helipad',
  'Private',
  'Tram',
  'Resort',
  'Jewellery',
  'Ice Cream',
  'Baptist',
  // 'Optician',
  'Department Store',
  'Horse Riding',
  'Paid',
  // 'Estate Agent',
  'Recreational Area',
  'Bookshop',
  'Gift Shop',
  'Bicycle Shop',
  // 'Discount Store',
  'Coast',
  // "Hotel Kids' Club",
  'Covered',
  'Chinese Cuisine',
  'Sandwiches',
  'Bicycle Rental',
  // 'Budget Hotel',
  'Sunni',
  'Wetland',
  'Greengrocer',
  'Sculpture',
  'Mosque',
  'Waterfall',
  // 'Travel Agency',
  'Theatre',
  'Fitness Center',
  'Statue',
  'Historical',
  'Platform',
  'Hotel Casino',
  'Caravan Site',
  'Taxi Stand',
  'Veterinary',
  // 'Octane 98',
  'Concrete',
  'Confectionery',
  'Inn',
  'Sports Shop',
  // 'Insurance Office',
  'Square',
  'Charging Station',
  'Group Home',
  'Cliff',
  'Lodge',
  'Pedestrian',
  'Reservoir',
  'Chemist',
  'Lutheran',
  'Orthodox',
  'Country House',
  'Picnic Shelter',
  'Laundry',
  'Garden',
  'Shell',
  'Computer Shop',
  'Unisex',
  // 'Multi Storey Parking',
  'Cable Car Station',
  'BBQ',
  'Cinema',
  'Stationery',
  // 'VISA Accepted',
  // 'Credit Cards Accepted',
  'Athletics',
  'Night Club',
  'Marina',
  "McDonald's",
  // 'MasterCard Accepted',
  'Pet Shop',
  'Cave',
  'Gravel',
  'Jogging',
  'Chicken',
  'Beverages Shop',
  'Latrine',
  'Cobblestone',
  'Protestant',
  'Shrine',
  'LPG',
  'Football',
  'Mexican Cuisine',
  // 'Underground Parking',
  // 'Lawyer',
  'Water Plant',
  'Sandy Beach',
  'Japanese Cuisine',
  'American Cuisine',
  'Nursing Home',
  'Castle Hotel',
  'Water Point',
  'Kebap',
  'War Memorial',
  'Newsagent',
  // 'Court Building',
  // 'Defibrillator',
  'Fitness Station',
  'Car Rental',
  'Shintoism',
  // 'Dry Cleaning',
  'Second Hand',
  'Hinduism',
  // 'One Way',
  'Tailor',
  'Volleyball',
  'Tyres Shop',
  'Tourist Information Office',
  'Art Center',
  'Forest',
  'Garden Centre',
  'Well',
  'Motorcycle Shop',
  'Ferry Terminal',
  'Fitness',
  'Trolleybus',
  'Wood',
  'Deli',
  'Toy Shop',
  'City',
  'Asian Cuisine',
  'Tomb',
  // 'Telecommunications Company',
  // 'Cosmetics Shop',
  'Anglican',
  'Methodist',
  'Indoor',
  // 'Copy Shop',
  'Indian Cuisine',
  'Farm Stay',
  'Beach Volleyball',
  'Educational Institution',
  'Men Only',
  'Alpine Hut',
  // 'Childcare',
  'Subway Sandwiches',
  'Residential Building',
  // 'Funeral Services',
  'Skateboard',
  'Climbing',
  'Driving School',
  'Women Only',
  'Recycling',
  'Allotment',
  'Recycling Centre',
  'Debit Cards Accepted',
  // 'Dedicated Smoking Area',
  'German Cuisine',
  'Shower',
  'Unpaved',
  'Metro Station',
  'City Block',
  'Observation Tower',
  'Park and Ride',
  'River',
  'Tobacco Shop',
  'Seafood Shop',
  'French Cuisine',
  'Boutique',
  'Tumulus',
  // 'Assisted Living',
  'Fireplace',
  // 'Motorcycle Parking',
  'Beer Garden',
  'Fire Pit',
  'Animals',
  'Farm Produce',
  'Non-government Organisation',
  'Ticket Shop',
  'Sushi',
  'Thai Cuisine',
  'Boules',
  'Photo Shop',
  'Organic',
  'Weather Shelter',
  'Table Tennis',
  'Starbucks',
  'Outdoor Equipment Shop',
  'Currency Exchange',
  'Bowls',
  'Seafood Cuisine',
  'Outdoor Pool',
  'Sauna',
  'Embassy',
  'Cricket',
  'Water Park',
  'City Wall',
  'Racetrack',
  'International Cuisine',
  'Greek Cuisine',
  'Lidl',
  'Dog Park',
  'Lighthouse',
  'Massage',
  'Muslim Cemetery',
  'E10',
  'Octane 92',
  'Circuit',
  'Music Store',
  'Houseware Shop',
  'Shooting',
  'Women Clothes',
  'Interior Decoration',
  'Esso',
  'Amex Accepted',
  'Steakhouse',
  'Wine Shop',
  'Holiday Park',
  'Temple',
  'Art Shop',
  'BP',
  'Prison',
  'Deutsche Post',
  'Maestro Accepted',
  'Burger King',
  'Tents',
  'Motorsports',
  // 'Jewish Culture',
  // 'Russian Orthodox',
  // 'Windmill',
  // 'Fish and Chips',
  // 'Evangelical',
  'Local Cuisine',
  // 'Paint Shop',
  // 'KFC',
  // 'International Airport',
  // 'IT Specialist',
  // 'Bookmaker',
  // 'Fabric Shop',
  'Pastry Shop',
  // 'Main Entrance',
  // 'Theme Park',
  // 'Greek Orthodox',
  // 'Aldi',
  // 'Carpenter',
  // 'Rugby',
  // 'Chair Lift',
  // 'Rock',
  // 'Presbyterian',
  // 'Wilderness Hut',
  // 'CNG',
  // 'Manor House',
  // 'Kitchen Studio',
  // 'Breakfast',
  // 'Military',
  // 'Lane Parking',
  // 'Hockey',
  // 'Netball',
  // 'National Park',
  // 'Self Service',
  // 'Pawnbroker',
  // 'Tartan',
  // 'Mennekes Socket',
  // 'Charity Shop',
  // 'Storage Rental',
  // 'Lottery',
  // 'Food Hall',
  // 'Budget-Friendly',
  // 'Total',
  // 'Gas Shop',
  // 'Ambulance Station',
  // 'Stream',
  // 'Bed Shop',
  // 'Art Gallery',
  // 'Facilities for Disabled Guests',
  // 'Noodles',
  // 'Pentecostal',
  // 'Monastery',
  // 'Tattoo Shop',
  'Zoo',
  'Baths',
  // 'Tunnel',
  // "Jehovah's Witness",
  'Skiing',
  'Minigolf',
  'Fish',
  // 'Employment Service',
  // 'Bunker',
  // 'Turkish Cuisine',
  // 'County',
  // 'Internet Cafe',
  // 'Accountant',
  // 'Water Mill',
  // 'Crafts Shop',
  // 'Luxury Tent',
  'Antiques Shop',
  // 'Studio',
  // 'R&D Office',
  // 'Mormon',
  // 'Winery',
  // 'Border Control',
  // 'Power Supply',
  // 'Fortification',
  // 'Vegetarian',
  'Glacier',
  'Beach Resort',
  // 'Gymnastics',
  // 'Dirt',
  // 'Fishing Spot',
  // 'Megalith',
  // 'Path',
  // 'Medical Supply Shop',
  // 'Bowling',
  // 'Spar',
  // 'Photo Studio',
  // 'Vietnamese Cuisine',
  // 'Casino',
  // 'Octane 91',
  // 'GTL Diesel',
  // 'Fashion Store',
  // 'Handball',
  // 'HiFi Shop',
  // 'Hill',
  // 'Ice Rink',
  // 'Gambling',
  // 'Backpackers',
  // 'Water Slide',
  // '7 ELEVEN',
  // 'Bitcoins Accepted',
  'Brewery',
  // 'Diners Club Accepted',
  'Hidden Gem',
  // 'Men Clothes',
  // 'Walgreens',
  'Mural',
  // 'Meadow',
  // 'Fort',
  // 'Donuts',
  'Pasta',
  // 'Boat Hotel',
  // 'General Store',
  // 'Architect',
  // 'Spanish Cuisine',
  // 'Electrician',
  'Cake',
  // 'Countryside',
  // 'Video Shop',
  'Gay-Friendly',
  // 'HGV Diesel',
  // 'Shoemaker',
  // 'Bog',
  // 'Bench',
  // 'Water Tap',
  // 'Tea Shop',
  // 'Diving',
  // 'Tourist Information Terminal',
  // 'Tea',
  // 'Baby Goods Store',
  // 'Volcano',
  // 'Outreach',
  // 'Love Hotel',
  // 'Grave',
  // 'Drag Lift',
  'Taco Bell',
  // 'Bag Shop',
  // 'Shia',
  // 'Perfumery',
  // 'Fries',
  // 'Metal Construction',
  // 'Hearing Aids',
  // 'Delivery',
  // 'Marsh',
  'Airport Terminal',
  // 'Grill',
  // 'Girocard Accepted',
  // 'Backcountry Camping',
  'Horse Racing',
  // 'Basic Hut',
  // 'Ferry Platform',
  // 'VISA Electron Accepted',
  'Bird Watching',
  // 'Bird Hide',
  'Mediterranean Cuisine',
  // 'Rollercoaster',
  // 'Stone',
  // 'Seasonal',
  // 'Newspaper Office',
  // 'Plumber',
  'Video Games',
  'Cabin',
  // 'Free Flying',
  // 'Children Clothes',
  // 'Cairn',
  // 'Ramen',
  // 'Gazebo',
  // 'Carpet Shop',
  // 'HGV Allowed',
  // 'Locksmith',
  // 'Baby Changing Facilities',
  'Canoe',
  // 'Wholesale',
  // 'Tax Advisor',
  // 'Public Building',
  // 'Ryokan',
  'Scuba Diving',
  // 'Korean Cuisine',
  // 'Caterer',
  // 'Health Centre',
  // 'Cycling',
  // "Editor's Choice",
  // 'City Gate',
  // 'Glaziery',
  // 'Underwear',
  // 'Political Party Office',
  'Motocross',
  // 'Vehicle Inspection',
  // 'Poma Lift',
  // 'Economy Hotel',
  // 'Karting',
  // 'Dairy Shop',
  // 'Hut',
  // 'Taoism',
  // 'HGV Not Allowed',
  // 'Q8',
  // 'Music School',
  // 'Erotic Shop',
  // 'Money Lender',
  // 'Chocolate',
  // 'Restricted Access',
  // 'Curtain Shop',
  // 'HVAC',
  // 'Viaduct',
  // 'Dojo',
  // 'Pebblestone',
  // 'Therapist',
  // 'Tex-Mex',
  // 'Jewish Cemetery',
  // 'Downhill',
  // 'Window Construction',
  // 'Cheese Shop',
  // 'Repsol',
  // 'Brothel',
  // 'UNESCO',
  // 'Chocolate Shop',
  // 'Advertising Agency',
  // 'Cape',
  // 'Creperie',
  // 'Money Transfer',
  // 'American Diner',
  // 'Seventh Day Adventist',
  // 'Hotel Beauty Services',
  // 'Appliances Shop',
  // 'Municipality',
  // 'Canal',
  // 'Cathedral',
  // 'Agip',
  // 'Handicraft',
  // 'Badminton',
  'Art',
  // 'Bathroom Furnishing Shop',
  // 'Frame Shop',
  // 'Notary Public',
  'Pancakes',
  // 'FamilyMart',
  // 'Tax Office',
  // 'Animal Shelter',
  'Shipwreck',
  // 'Bronze',
  // 'Electronics Repair',
  // 'Octane100',
  // 'Archery',
  // 'LAWSON',
  // 'Coworking Space',
  // 'Physician',
  // 'Reformed',
  // 'Animal Breeding',
  // 'Petrobras',
  // 'Field Hockey',
  // 'Octane 80',
  // 'Lukoil',
  // 'E-cigarettes Shop',
  // 'Swamp',
  // 'Boat Rental',
  // 'Sanitary Dump Station',
  // 'Gunter Demnig',
  // 'Ten Pin',
  // 'Wellness',
  // 'Dress Maker',
  // 'Amusement Ride',
  // 'Padel (Paddle)',
  // 'Nutrition Supplements Shop',
  // 'T-bar Lift',
  // 'Dogs Allowed',
  // 'Yoga',
  // 'Skating',
  // 'Register Office',
  // 'E85',
  // 'Pelota',
  // 'Tesco',
  // 'Renault',
  // 'Bare Rock',
  // 'Chademo Socket',
  // 'Futsal',
  // 'Exercise',
  // 'Vegan',
  // 'Painter',
  // 'Arabic Cuisine',
  // 'Watches Shop',
  // 'Ranger Station',
  // 'Military Office',
  // 'Energy Supplier',
  // 'Octane 87',
  // 'Electrical Shop',
  // 'Waste Treatment',
  // 'Palace',
  // 'Fishing Equipment',
  // 'DKV Accepted',
  // 'Natural Monument',
  // 'Tapas',
  // 'Hot Dogs',
  // 'Gardener',
  // '360° Content',
  // 'Agrarian Shop',
  // 'Stonemason',
  // 'Grassland',
  // 'Herbalist',
  // 'ENEOS',
  // 'Accessible with Permit',
  // 'Circle K',
  // 'Scrub',
  // 'Open Fire Allowed',
  // 'CCS 2 Socket',
  // 'Softball',
  // 'Caltex',
  // 'UTA Accepted',
  // 'Chess',
  // 'Aircraft',
  // 'Business',
  // 'Sawmill',
  // 'Bandera Blanca',
  // 'AdBlue',
  // 'Магнит',
  // 'Russian Cuisine',
  // 'Ford',
  // 'Gate',
  // 'Battlefield',
  // 'Mountain Pass',
  // 'Motorcycle Repair Shop',
  // 'Modern Architecture',
  // 'Toll',
  // 'Primary School',
  // 'YPF',
  'Rapids',
  // 'Ipiranga',
  // 'Magic Carpet',
  // 'Gaelic Games',
  // 'Band Stand',
  // 'Graffiti',
  // 'Amusement Arcade',
  // 'Curry',
  // 'Eco-Friendly',
  // 'Cannon',
  // 'Chevron',
  // 'Radiotechnics Shop',
  // 'Toyota',
  // 'BMX',
  // 'Mobil',
  // 'Riad',
  // 'Weigh Bridge',
  // 'Saddle',
  // 'Indonesian Cuisine',
  // 'Language School',
  // 'Aral',
  // 'Model Aerodrome',
  // 'Honda',
  // 'Carport',
  // 'State',
  'Ice Skating',
  // 'New Apostolic',
  // 'Exit Only',
  // 'Tamoil',
  // 'Indoor Pool',
  // 'Trampoline',
  // 'Peugeot',
  // 'Foundation Office',
  // 'Chemical Toilet',
  // 'Sausage',
  // 'Ethiopian Cuisine',
  // 'Salads',
  // 'Volkswagen',
  // 'Religious Merchandize',
  // 'Logistics Company',
  'Reef',
  // 'Roofer',
  // 'Key Cutter',
  // 'Gondola Lift',
  'Winter Sports',
  // 'Bio Diesel',
  // 'Petron',
  // 'Episcopal',
  // 'Summer',
  // 'Lebanese Cuisine',
  // 'Leather Store',
  // 'Portuguese Cuisine',
  'Fishing',
  // 'Stables',
  // 'Settlement',
  // 'Crematorium',
  // 'Rooftop Parking',
  // 'Greek Catholic',
  // 'Cable Car',
  // 'Food Bank',
  // 'Bay',
  // 'Wholefoods',
  // 'Physiotherapist',
  // 'Sewing Shop',
  // 'Billiards',
  // 'Upholsterer',
  // 'Georgian Cuisine',
  // 'Borough',
  'Pottery',
  // 'Easy Piste',
  // 'Installation',
  // 'Juice',
  // 'Region',
  // 'Bagels',
  // 'Watchmaker',
  'Disc Golf',
  // 'Scuba Diving Shop',
  // 'Beef Bowl',
  // 'Shed',
  // 'Supervised',
  'Gravel Beach',
  // 'Oriental Cuisine',
  // 'Enel',
  // 'Nine Pin',
  'Nudist Beach',
  // 'Grocery',
  // 'Blacksmith',
  // 'Club',
  // 'Soba',
  // 'Cepsa',
  // 'Capsule Hotel',
  // 'Water Tower',
  // 'Tanning Salon',
  // 'Polish Cuisine',
  // 'Emergency Assembly Point',
  // 'Gym',
  // 'Opel',
  // 'Caribbean Cuisine',
  // 'Builder',
  // 'Filipino Cuisine',
  // 'Sand Pit',
  // 'Milestone',
  // 'Valley',
  // 'Observatory',
  // 'Drive-through',
  // 'Terrace',
  // 'Lighting Shop',
  // 'Carousel',
  // 'Intermediate Piste',
  // 'Pet Grooming',
  // 'Exxon',
  // 'Hot Springs',
  // 'Water Shop',
  // 'Weapons Shop',
  // 'Basilica',
  // 'Wedding Clothes',
  // 'Rope Tow',
  // 'Sinkhole',
  // 'Party Shop',
  // 'Bavarian Cuisine',
  // 'Shoe Repair Shop',
  // 'Peruvian Cuisine',
  // 'Rowing',
  // 'OMV',
  // 'BMW',
  // 'African Cuisine',
  // 'Tesla Supercharger',
  // 'Sikh',
  // 'Ministry',
  // 'Tiles Shop',
  // 'Sparkasse',
  // 'Texaco',
  // 'Avia',
  // 'Sun Shelter',
  // 'Orlen',
  // 'Hot Water',
  // 'Sports Clothes',
  // 'Painting',
  // 'Water Utility Office',
  // 'Naftal',
  // 'Mercedes-Benz',
  // 'Brazilian Cuisine',
  // 'Pillbox',
  // 'Slide',
  // 'Obelisk',
  // 'Frozen Food Shop',
  // 'Distillery',
  // 'Photo Laboratory',
  // 'Beekeeper',
  // 'Military Airfield',
  // 'Aqueduct',
  // 'Convention Centre',
  // 'Sailing',
  // 'Village Hall',
  // 'Strip Club',
  // 'Pemex',
  // 'Youth Centre',
  // 'Tibetan',
  // 'Dormitory',
  // 'Dive Centre',
  'Lunch',
  // 'Alternative Healthcare',
  // 'Mortuary',
  // 'Public Prosecutor Office',
  // 'Lift Station',
  // 'Galp',
  // 'Trail Riding Station',
  // 'Retirement Home',
  // 'Racquet',
  // 'Roller Skating',
  // 'Hacker Space',
  'Aquarium',
  // 'Printing Shop',
  // 'Argentinian Cuisine',
  // 'Baroque Architecture',
  // 'CCS 1 Socket',
  // 'Car Sharing',
  // 'Historic Building',
  // 'Summer Toboggan',
  // 'Buschenschank',
  // 'Parking Garage',
  // 'Customs',
  // 'Window Blind Shop',
  // 'Historicism',
  // 'Secondary School',
  // 'Garage Box',
  // 'Game Shop',
  'Spa',
  // 'Parish Hall',
  // 'Heuriger',
  // 'Ship',
  // 'Thai Massage',
  // 'Gay and Lesbian',
  // 'Flooring Shop',
  // 'Forestry Office',
  // 'Tiler',
  // 'Desserts',
  // 'Archipelago',
  // 'Campanile',
  // 'Emergency Service',
  'Art Museum',
  'Botanical Garden',
  // 'Maze',
  // 'Cannabis Shop',
  // 'MOL',
  // 'Balkan Cuisine',
  // 'Times 24th',
  // 'Ice Stock',
  // 'Long Jump',
  // 'Public Hall',
  // 'Fire Hydrant',
  // 'Persian Cuisine',
  // 'Baby Clothes',
  // 'Joiner',
  // 'Squash',
  // 'Disused',
  // 'Horseshoes',
  // 'Winter',
  // 'Hunting Shop',
  // 'Building Materials',
  // 'Club Home',
  // 'Bullfighting',
  // 'Boxing',
  // 'History Museum',
  // 'Rental',
  // 'Bucket Toilet',
  // 'Geoglyph',
  // 'Vacuum Cleaner Shop',
  // 'Surfing',
  // 'Shopping Area',
  // 'War Grave',
  // 'Safeway',
  // 'Waste Basket',
  // 'Petting Zoo',
  // 'Columbarium',
  // 'Synagogue',
  // 'Cottage',
  // 'Hanami',
  // 'Ski Jump',
  // 'Martial Arts',
  // 'Charity',
  // 'Hobby Shop',
  // 'Fried Chicken',
  // 'Escape Game',
  // 'Ministerie van Oorlog',
  // 'Boat Shop',
  // 'Sanatorium',
  // 'Zip Line',
  // 'Snacks',
  // 'Paintball',
  // 'Castle Ruins',
  // 'Weather Bubble',
  // 'Community Hall',
  // 'Fuel Shop',
  // 'Psychotherapist',
  // 'Heath',
  'Tacos',
  // 'Fireplace Shop',
  // 'Research Institute',
  // 'Mausoleum',
  // 'Outdoor Baths',
  // 'Guides Office',
  'Music Venue',
  // 'Moroccan Cuisine',
  // 'Denim Clothes',
  // 'Rock Shelter',
  // 'Clock',
  // 'Climbing Frame',
  // 'Reed-bed',
  // 'Geyser',
  // 'MINISTOP',
  // 'PTT',
  // 'サークルK',
  // 'Croatian Cuisine',
  // 'Tombstone',
  // 'Parking Shed',
  // 'Vending Machine',
  // 'Summer Camp',
  // 'Tesla Supercharger Socket',
  // 'Swimming Pool Equipment Shop',
  // 'Pyrotechnics Shop',
  // 'Matsuya',
  // 'Life Guard Tower',
  // 'Toboggan',
  // 'Eni',
  // 'Karate',
  // 'Extinct Volcano',
  // 'Lacrosse',
  // 'Strolling Area',
  // 'Workwear',
  // 'Frozen Yogurt',
  // 'Apple Pay',
  // 'Mangrove',
  // 'Barn',
  // 'Construction Company',
  // 'Play Structure',
  // 'Hookah Lounge',
  // 'Austrian Cuisine',
  // 'Judo',
  // 'Wine Cellar',
  'Planetarium',
  // 'Soup',
  // 'Social Club',
  // 'Greenhouse',
  'Hiking & Camping',
  // 'Orienteering',
  // 'Korfball',
  // 'Bistro',
  // 'European Cuisine',
  // 'Scout Camp',
  // 'Buffet',
  // 'Lamps Shop',
  // 'Paddle Tennis',
  // 'Mosaic',
  // 'Routex Accepted',
  // 'Lingerie Shop',
  // 'City Park',
  // 'Irish Cuisine',
  // 'Steps',
  // 'Slipway',
  // 'Marble',
  // 'Remote Controlled Cars',
  // 'English Heritage',
  // 'Dog Racing',
  // 'Agricultural Works',
  // 'Government Building',
  // 'Gothic Architecture',
  // 'Ultralight Aviation',
  // 'International',
  // 'Lao Cuisine',
  // 'British Cuisine',
  // 'Accessories Shop',
  // 'Rescue Station',
  // 'Moving Company',
  // 'Hats Shop',
  // 'Deck Shuffleboard',
  // 'Big Wheel',
  // 'Private Airport',
  // 'Preem',
  // 'Hungarian Cuisine',
  // 'Dance',
  // 'Petrol',
  // 'Bungalow',
  // 'Middle Eastern Cuisine',
  // 'Event Venue',
  // 'Danish Cuisine',
  // 'Ethanol',
  // 'Dog Training',
  // 'SoftBank',
  // 'Sculptor',
  // 'Swinger Club',
  // 'DOUTOR',
  // 'Traditional Cuisine',
  // 'Wildlife Hide',
  // 'Bolivian Cuisine',
  // 'Water Sports Shop',
  // 'Shopping Center',
  // 'Sports Venue',
  // 'Ridge',
  // 'Curling',
  // 'Necropolis',
  // 'Trailer Park',
  // 'Spice Shop',
  // 'Candle Shop',
  // 'Car Racing',
  // 'Pétanque',
  // 'Mountain Rescue',
  // 'Pottery Shop',
  // 'HGV Parking',
  // 'Model Shop',
  // 'Neoclassical Architecture',
  // 'Smoothies',
  // 'Tinsmith',
  // 'Household Items',
  // 'Cultural Center',
  // 'Haberdashery',
  // 'Petrom',
  // 'Latin American Cuisine',
  // 'Bubble Tea',
  // 'Shotput',
  // 'Friterie',
  'River Bank',
  // 'Taiwanese Cuisine',
  // 'Bumper Cars',
  // 'Cruise',
  // 'Laundry Service',
  // 'Shawarma',
  // 'Water Skiing',
  // 'Dancing School',
  'Contemporary Art',
  // 'Health Resort',
  // 'Onsen',
  // 'Anime Shops',
  // 'IP',
  // 'Empanada',
  // 'Novice Piste',
  // 'Souvenir Shop',
  // 'Dock',
  // 'BERNMOBIL',
  // 'Taekwondo',
  // 'Udon',
  // 'Camera Shop',
  // 'Eclectic Architecture',
  // 'Croquet',
  // 'Scaffolder',
  // 'Exhibition Hall',
  // 'Astronomical Observatory',
  // 'WOG',
  'Solarium',
  // 'Lifeguard Base',
  // 'Water Available',
  // 'Plasterer',
  // 'Book Binder',
  // 'Scree',
  // 'Shopping Street',
  // 'Filming Location',
  // 'Province',
  // 'Relief',
  // 'Aerial Views',
  // 'Malagasy Cuisine',
  // 'Military Airport',
  // 'Dormant Volcano',
  // 'Voodoo',
  // 'OKQ8',
  // 'Nursery',
  // 'Paragliding',
  // 'Furniture Maker',
  // 'Ski Rental',
  // 'Discount Shop',
  // 'Rehabilitation',
  // 'Advanced Piste',
  // 'Apple',
  // 'Table Soccer',
  // 'Optometrist',
  // 'Telescope',
  // 'Cold Water Only',
  // 'Ski School',
  // 'Laboratory',
  // 'Cuban Cuisine',
  // 'Concert Hall',
  // 'Modern Art',
  // 'Clothing-optional Beach',
  // 'Paleontological Site',
  // 'Tourist Train',
  // 'Falafel',
  // 'Capital',
  // 'Tea House',
  // 'Military Barracks',
  // 'Neste',
  // 'Golf Pin',
  // 'Cryptocurrencies Accepted',
  // 'Cock Fighting',
  // 'Office Supplies',
  // 'Google Pay',
  // 'Floorer',
  // 'Nepalese Cuisine',
  // 'Waffles',
  // 'Local Products',
  // 'Street',
  // 'Thermal Baths',
  // 'Wildlife',
  // 'Boat Builder',
  // 'Kite Surfing',
  // 'Chimney',
  // 'Insect Hotel',
  // 'Water Rescue Station',
  // 'Renaissance Architecture',
  // 'Hawaiian Cuisine',
  // 'Log Flume',
  // 'Romanesque Architecture',
  // 'Dining District',
  // 'Petroglyph',
  // 'Carpet Layer',
  // 'Philharmonic',
  // 'Food Market',
  // 'E20',
  // 'Marketplace',
  // 'Organic Shop',
  // 'Slovnaft',
  // 'Preschool',
  // 'Scout Hut',
  // 'Mine',
  // 'Dryer',
  // 'Exhibition',
  'Water Sports',
  // 'Barefoot',
  // 'Hofer',
  // 'Boathouse',
  // 'Facultative School',
  // 'Biogas',
  // 'Country',
  // 'Pies',
  'Contemporary Architecture',
  // 'Dry Toilet',
  // 'Czech Cuisine',
  // 'Belgian Cuisine',
  // 'School Yard',
  // 'Baker',
  // 'Jamaican Cuisine',
  // 'Rompetrol',
  // 'Gyros',
  // 'Uzbek Cuisine',
  // 'Grilled Meat',
  // 'Cantonese Cuisine',
  // 'Heated',
  // 'Neo-Gothic Architecture',
  // 'Airfield',
  // 'SCAME Socket',
  // 'St1',
  // 'Military Shooting Range',
  // 'Water Tank',
  'Amtrak',
  // 'Skyscraper',
  // 'Fusion Cuisine',
  // 'Bernhard Düttmann',
  // 'Weir',
  // 'Syrian Cuisine',
  // 'Entertainment District',
  // 'Jace',
  // 'Saddler',
  // 'Medieval',
  // 'Communication Shop',
  // 'Railway Museum',
  // 'Historical District',
  // 'Fencing',
  // 'Ski Resort',
  // 'Brasserie',
  // 'Active Volcano',
  // 'Podiatrist',
  // 'J-bar Lift',
  // 'Pakistani Cuisine',
  // 'Bird Sanctuary',
  // 'Piste',
  // 'Opera',
  // 'Hunting Stand',
  // 'Afghan Cuisine',
  // 'Wedding Saloon',
  // 'Charles-Auguste Lebourg',
  // 'Via Ferrata',
  // 'Ski Shop',
  // 'Piadina',
  // 'ERG',
  // 'Drop Tower',
  // 'Snooker',
  'Art Deco',
  // 'River Rafting',
  // 'Statoil',
  // 'Historic House Museum',
  // 'Art Noveau Architecture',
  // 'Burial Site',
  // 'Bicycle Parking',
  'Vineyard',
  // 'Wading Pool',
  // 'Couscous',
  // 'Mongolian Cuisine',
  // 'Souvlaki',
  // 'Lasertag',
  // 'Speech Therapist',
  // 'Classicism',
  // 'Hut Circle',
  // 'Ukrainian Cuisine',
  // 'Hot Baths',
  // 'Kids',
  // 'Cajun Cuisine',
  // 'Mini Tennis',
  'Cross Country Skiing',
  // 'Polo',
  'National Museum',
  // 'Outdoor Shower',
  // 'Organisation Todt',
  // 'Burritos',
  // 'Funicular',
  // 'Family Friendly',
  // 'Bobsleigh Track',
  // 'Afriquia',
  // 'Swiss Cuisine',
  // 'Science Museum',
  'Lagoon',
  // 'Stele',
  // 'Thermal Insulation',
  // 'Play House',
  'Beer',
  // 'WWII',
  // 'Canteen',
  // 'Golf Shop',
  // 'Indoor Playground',
  // 'Open-air Museum',
  // 'Art Nouveau Style',
  // 'GeldKarte Accepted',
  // 'Column',
  // 'Wilhelm Riphahn',
  // 'Festival Grounds',
  // 'Observation Deck',
  // 'Rope Park',
  'Scenic Lookout',
  // 'Armenian Cuisine',
  // 'Swing Carousel',
  // 'Dark Ride',
  // 'Royal Residence',
  // 'Bicycle Transport',
  // 'I Amsterdam City Card',
  // 'Informal Campground',
  // 'Sarcophagus',
  // 'Houseboat',
  // 'Fell',
  // 'Crane',
  // 'Pirate Ship',
  // 'Archaeological Museum',
  // 'Speedway',
  // 'Tent',
  // 'Meal Vouchers Accepted',
  'Mountain',
  // 'Trampoline Park',
  // 'Art Collections',
  // 'Vienna Card',
  // 'Tesla Standard Socket',
  // 'Wet Season',
  'Hunting Lodge',
  'Amusement Park',
  // 'Workout',
  // 'Military Only',
  // 'Babies',
  // 'Basque Cuisine',
  // 'Swedish Cuisine',
  // 'Arch Bridge',
  'Circus',
  'Street Art',
  // 'Lookout',
  // 'Roman',
  // 'Whirlpool',
  // 'Musical Theatre',
  // 'Abbey',
  // 'Max Pommer',
  // 'Emergency Phone',
  // 'Dental Technician',
  // 'Academy',
  // 'Victorian Architecture',
  // 'Samsung Pay',
  // 'Catering',
  // 'Conservative',
  // 'Sun Protection',
  // 'Castrum',
  // 'Fondue',
  // 'Coastal Views',
  // 'Emergency Landing Site',
  // 'Drama',
  // 'Egyptian Cuisine',
  // 'Modernist Architecture',
  // 'Public Park',
  // 'Sexual Massage',
  // 'Dog School',
  // 'Australian Cuisine',
  // 'Lock Gate',
  // 'Chimney Sweeper',
  // 'Flea Market',
  // 'Michelin Star',
  // 'Henry Moore',
  // 'Gliding',
  // 'Dutch Cuisine',
  // 'Rock Formation',
  // 'Sports Facility',
  // 'Alfred Fischer',
  // 'Emergency Evacuation Centre',
  // 'Suspension Bridge',
  // 'Protected Area',
  // 'Outcrop',
  // 'Wildcamp',
  // 'Midwife',
  // 'Tradition',
  // 'Hans Werner Eggeling',
  // 'Promenade',
  // 'Marine Life',
  // 'Flora',
  // 'Amsterdam Holland Pass',
  // 'Turkish Bath',
  // 'Court',
  // 'Fashion',
  // 'Village Green',
  // 'Creole',
  // 'Game of Thrones',
  // 'Military Trench',
  // 'CitéCréation',
  // 'Print Maker',
  // 'Plank Walkway',
  // 'Biographical Museum',
  // 'Colombian Cuisine',
  // 'Wok',
  // 'Dogs',
  // 'Boat Ride',
  // 'Walkway',
  // 'Pablo Picasso',
  // 'Religious Site',
  // 'London Pass',
  // 'Mud',
  // 'Office Building',
  // 'Bangladeshi Cuisine',
  // 'Waste Disposal',
  // 'Performance',
  // 'Liquid Hydrogen',
  // 'Sail Maker',
  // 'Parquet Layer',
  // 'Building',
  // 'Flowers',
  // 'Tibetan Cuisine',
  // 'Earthwork',
  'Wine',
  // 'Classic Art',
  // 'Skatepark',
  // 'Paris Pass',
  // 'Jewish Cuisine',
  // 'Chiropractor',
  // 'Street Market',
  // 'Karaoke',
  // 'Yogurt',
  // 'Firenze Card',
  // 'Meeting Room',
  // 'Full Service',
  // 'Bulgarian Cuisine',
  // 'Baguette',
  // 'Scenic',
  // 'Copenhagen Card',
  // 'Shiro',
  // 'Caucasian Cuisine',
  // 'National Trust for Scotland',
  // 'Residence',
  // 'Baroque Art',
  // 'Technology Museum',
  // 'Kremlin',
  // 'Souvenirs',
  // 'Port',
  // 'Lego',
  // 'Sports Airport',
  // 'Luxurious Brands',
  // 'Barcelona Card with Guidebook',
  'Coffee',
  // 'Welcome Break',
  // 'Barcelona Discount Card',
  // 'Serbian Cuisine',
  // 'Listed Building',
  'Natural History Museum',
  // 'Fish Shop',
  // 'Chinese Massage',
  // 'Booking Required',
  // 'Romanian Cuisine',
  // 'Halal Cuisine',
  // 'Berlin WelcomeCard',
  // 'Parklet',
  // 'Blood Donation',
  // 'Cambodian Cuisine',
  'State Park',
  'Climbing Wall',
  // 'Berlin Pass',
  // 'Caldera Rim',
  // 'Boat Storage',
  // 'Basket Maker',
  // 'Olympics',
  // 'Constructivism',
  // 'Cultural District',
  'Cliff Diving',
  // 'Art School',
  // 'Monet',
  // 'Vienna Pass',
  // 'Bingo',
  // 'Military Museum',
  // 'Swing',
  // 'Winter Only',
  // 'Moto',
  // 'Mansion',
  // 'Gothic Art',
  // 'Rococo Architecture',
  // 'Scheduled Monument',
  // 'Sweets',
  // 'Historic Scotland Explorer Pass',
  // 'Johannes Wiedewelt',
  // 'Antony Gormley',
  // 'National Monument',
  // 'Ancient Greece',
  // 'Casemate',
  // 'Philippine Cuisine',
  // 'Decorative Arts Museum',
  // 'Frescoes',
  // 'Renaissance Art',
  // 'Bell Tower',
  // 'Military Checkpoint',
  // 'Truck Wash',
  // 'Wine Bar',
  // 'Thai Suki',
  // 'Volcanic Vent',
  // 'Metano',
  // 'Mobile Homes',
  // 'Canadian Cuisine',
  // 'Cocktail Bar',
  // 'Senegalese Cuisine',
  // 'Therapeutic Massage',
  // 'Basque Cider House',
  // 'Elementary School',
  // 'Trail',
  // 'Scenic Route',
  // 'Street Food',
  'Sculpture Garden',
  'Ancient Art',
  // 'Weather Monitoring',
  // 'Concert',
  // 'War Museum',
  // 'Israeli Cuisine',
  // 'Rubens',
  // 'Gite',
  // 'Foot Bath',
  // 'Pit',
  // 'Avenue',
  // 'Ferris Wheel',
  // 'Religious Museum',
  // 'Petroleum Well',
  'Van Gogh',
  // 'Luxury',
  // 'Canyon',
  // 'Agustín Ibarrola',
  // 'Santiago Calatrava',
  // 'Family Centre',
  // 'Expert Piste',
  // 'Francis Kéré',
  // 'Monkeys',
  // 'Swabian Cuisine',
  // 'ASFINAG',
  // 'Maritime Museum',
  // 'Exhibition Building',
  // 'Volker Pfannkuche',
  // 'Olof Thunström',
  // 'Baby Feeding Room',
  // 'Meteorological Observatory',
  // 'City Center',
  // 'Historical Town',
  // 'Open-air Market',
  // 'Venezia Unica City Pass',
  // 'Cantilever Bridge',
  // 'Kosher Cuisine',
  // 'Driving Range',
  // 'Postmodern Architecture',
  // 'Ballet',
  // 'Japanese Culture',
  // 'Citadel',
  // 'Autogrill',
  // 'Safari',
  // 'New York CityPass',
  // 'Georgian Architecture',
  // 'Asian Art',
  // 'Rembrandt',
  // 'Music',
  // 'Neo-Renaissance Architecture',
  // 'Paul Cézanne',
  // 'Nature Trail',
  // 'Cabaret',
  // 'Gaudí',
  // 'Chinatown',
  // 'Interactive',
  // 'Gustav Vigeland',
  // 'Munitions Bunker',
  // 'Scotch Whisky',
  // 'Nuclear Test Site',
  // 'Salvador Dalí',
  // 'Store',
  // 'Facade',
  // 'Clothes',
  // 'Royal Palace',
  // 'Dry Season',
  // 'Horses',
  // 'Waterfront',
  // 'Seaside',
  // 'Plegt-Vos',
  // 'Ancient Rome',
  // 'Budapest Card',
  // 'Azerbaijan Cuisine',
  // 'Verona Card',
  // 'Culture',
  // 'Birds',
  // 'Madrid Card',
  // 'Andy Warhol',
  // 'HGV Local Traffic Only',
  // 'Parliament',
  // 'Snorkeling',
  // 'Alvar Aalto',
  // 'Lookout Tower',
  // 'Harry Potter',
  // 'Dome',
  'Farmers Market',
  // 'Joan Miró',
  // 'Go Los Angeles® Card',
  'Live Music',
  // 'Puppet Theater',
  // 'Döner',
  // 'Moscow CityPass',
  // 'Sand Baths',
  // 'Animal Training',
  // 'Beer & Brewery Tours',
  // 'Buddha',
  // 'Japanese Architecture',
  // 'Japanese Garden',
  // 'Catalan Modernism',
  // 'Photography',
  // 'Bullring',
  // 'A. Sélonier',
  // 'Bears',
  // 'Shiatsu Massage',
  // 'Horse Walker',
  // 'Henri Matisse',
  // 'West End Theater',
  // 'Lake Baths',
  // 'Rooftop Pool',
  // 'Dining Experience',
  // 'Cold War',
  // 'Brutalist Architecture',
  // 'Norman Architecture',
  // 'Frankfurt Card',
  // 'PKN Orlen',
  // 'Arch',
  // 'Science',
  'Wax Museum',
  // 'Show',
  // 'Frank Lloyd Wright',
  // 'Le Corbusier',
  // 'Bronze Statue',
  // 'Renoir',
  // 'Gourmet',
  // 'Zaha Hadid',
  // 'Candy Store',
  // 'Hard Rock Cafe',
  // 'Pagoda',
  // 'Fritz Schumacher',
  // 'Harbor',
  // 'Comedy Theater',
  // 'Falconry',
  // 'Christmas Market',
  // 'Jackson Pollock',
  // 'Legend',
  // 'Theme Restaurant',
  // 'Neo-Baroque Architecture',
  // 'Heinrich Bergthold',
  // 'Banz',
  // 'Brunch',
  // 'Clock Tower',
  // 'Leonardo da Vinci',
  // 'Japanese Art',
  // 'Neolithic',
  // 'High School',
  // 'Madame Tussauds',
  // 'A. Champy',
  // 'Goya',
  // 'Stained Glass',
  // 'Trestle',
  // 'Prussian Cultural Site',
  // 'Photography Museum',
  // 'School for Blind',
  // '230V',
  // 'Visitor Center',
  // 'Landes',
  // 'Berlin Wall',
  // 'Historical Village',
  // 'Beach Resort Hut',
  // 'Munich CityTourCard',
  // 'Convent',
  // 'Beaux-Arts Architecture',
  // 'Traditional Crafts',
  // 'Lithuanian Cuisine',
  // 'Per Kirkeby',
  // 'El Greco',
  // 'RoadChef',
  // 'Audiologist',
  // 'L. C. Heckly',
  // 'Entertainment Venue',
  // 'Design Museum',
  // 'Transport Museum',
  // 'Blockhouse',
  // 'Wassily Kandinsky',
  // 'Colonial Architecture',
  // 'Moorish Architecture',
  // 'Shingle',
  // 'Fish Market',
  // 'Zoology Museum',
  // 'Vintage',
  // 'Modernisme Architecture',
  // 'Literary Museum',
  // 'Michelangelo Buonarroti',
  // 'Pilgrimage',
  // 'Marijuana',
  // 'Cherry Blossom Viewing',
  // 'Sandbox',
  // 'Cistercian',
  // 'HGV Delivery Only',
  // 'Science Centre',
  // 'Light Show',
  // 'Balance Beam',
  // 'Football Venue',
  // 'Bleachers',
  // 'Accessible with License',
  // 'Weird',
  // 'Venice Museum Pass',
  // 'DüsseldorfCard ',
  // 'Arcade',
  // 'Fine Arts',
  // 'Shopping Arcade',
  // 'Expressionist Architecture',
  // 'Exhibition Space',
  // 'Stage',
  // 'Jewish History',
  // 'Archaeology',
  // 'Open-air Gallery',
  // 'Landscape',
  // 'H. Cambon',
  // 'Go San Francisco Card',
  // 'Prague City Pass',
  // 'Classical Architecture',
  // 'Retail',
  // 'Roman Period',
  // 'Hamburg Card',
  // 'Specialty Coffee',
  // 'Renaissance Revival Architecture',
  // 'National Gallery',
  // 'Boulevard',
  // 'Flower Market',
  // 'Indoor Market',
  // 'Raphael',
  // 'Albrecht Dürer',
  // 'Neste Oil',
  // 'Freeride',
  // 'Crypt',
  // 'Fresh Produce',
  'Pizzeria',
  'State Forest',
  // 'Priory',
  // 'Chateau',
  // 'Flamenco',
  // 'Public Space',
  // 'Stairs',
  // 'Royal',
  // 'Sanctuary',
  // "World's Fair Architecture",
  // 'Titian',
  // 'Natural Pool',
  // 'Milano Card',
  // 'Factory Tour',
  // 'Outlet Mall',
  // 'Hong Kong and Macau Attractions Pass',
  // 'Khmer Architecture',
  // 'Music Club',
  // 'Organ',
  // 'Cheese',
  // 'Max Ernst',
  // 'Chocolate Factory',
  // 'Headquarters',
  // 'Oscar Niemeyer',
  // 'Traditional Medicine',
  // 'Museum Complex',
  // 'Fashion Museum',
  // 'Mannerist Architecture',
  // 'Anglican Church',
  // 'Communication Tower',
  // 'Animal Park',
  // 'Building Complex',
  // 'Night Market',
  // 'Vegetables',
  // 'Jungle Gym',
  // 'Francis Bacon',
  // 'Piet Mondrian',
  // 'Hieronymus Bosch',
  // 'Historic Street',
  // 'Mughal Architecture',
  // 'Hammam',
  // 'Baroque Revival Architecture',
  // 'Amphitheater',
  // 'Marionette',
  // 'Royal Park',
  // 'Prehistoric',
  // 'OMNIA Vatican and Rome Card',
  // 'Neo-Romanesque Architecture',
  // 'Agora',
  'Art District',
  // 'Benedictine',
  // 'Parking Entrance',
  // 'Egyptian Collection',
  // 'Symbol',
  // 'Arena',
  // 'Hundertwasser',
  'Public Art',
  'Ceramics',
  // 'Disney',
  // 'Unique',
  // 'Dolphins',
  // 'Thrill Rides',
  // 'Toy Museum',
  // 'Riverside',
  // 'Zen Buddhist',
  // 'Railway Bridge',
  // 'Greek Revival Architecture',
  // 'Limestone',
  // 'Fruit',
  // 'Sheeps',
  // 'American Art',
  // 'Paul Klee',
  // 'Vermeer',
  // 'Holocaust',
  // 'Passage',
  // 'Outlet',
  'Rose Garden',
  // 'Moorish Revival Architecture',
  // 'Fishing Village',
  // 'Spices',
  // 'Presidential Palace',
  // 'Urban Space',
  // 'High-tech Architecture',
  // 'William Shakespeare',
  // 'Music Museum',
  // 'Church of England',
  // 'Iranian Cuisine',
  // 'Édouard Manet',
  // 'Byzantine Architecture',
  // 'Nurnberg Card',
  // "Giant's Kettle",
  // 'Functionalism',
  // 'Adventure',
  // 'Aerospace Museum',
  // 'Archive',
  // 'Naval Museum',
  // 'Chocolate Museum',
  // 'Glacial Lake',
  // 'Water Transport',
  // 'Legoland',
  // 'Traditional Architecture',
  // 'Colonnade',
  // 'Entertainment Center',
  'Mountain Range',
  // 'Ottoman Architecture',
  // 'Marc Chagall',
  // 'Gossip Girl',
  // 'Military Naval Base',
  // 'Laser Accepted',
  // 'Arete',
  'Tropical Garden',
  // 'Bazaar',
  // 'Campus',
  // 'Aerial Lift',
  // 'Temple Complex',
  // 'Wall',
  // 'Car Museum',
  // 'Boats',
  // 'Literature',
  // 'Traditional Art',
  // 'Folk Culture',
  // 'Commercial District',
  // 'Jewish Museum',
  // 'Cultural Museum',
  // 'Henri Rousseau',
  // 'Albert Gleizes',
  // 'Delacroix',
  // "Hadrian's Wall",
  // 'Geothermal Area',
  // 'Stone Bridge',
  'Rock Climbing',
  // 'Children Museum',
  // 'Chicago Explorer Pass',
  // 'Booking Recommended',
  // 'Beehive',
  // 'Cheap',
  // 'Zen',
  // 'Anime',
  // 'Greek Temple',
  // 'Workshop',
  // 'Bauhaus',
  // 'Production',
  // 'Gluten-Free',
  // 'Electronics',
  // 'Triumphal Arch',
  // 'Street Food Stall',
  // 'University Museum',
  // 'Gelateria',
  // 'Cars',
  // 'Orchards',
  // 'Traditional Market',
  // 'Sydney Attractions Pass',
  // 'Gorge',
  // 'Desert',
  // 'Mark Rothko',
  // 'Diving Platform',
  // 'Monastic House',
  // 'Go Chicago Card',
  // 'Erratic Block',
  // 'Moor',
  // 'Film',
  // 'Impressionism',
  // 'Greek Architecture',
  // 'Market Hall',
  // 'Forum',
  'Microbrewery',
  // 'Meat',
  // 'Jazz Club',
  // 'Thai Culture',
  // 'Hot Chocolate',
  // 'Holocaust Memorial',
  // 'Imperial Palace',
  // 'Film Studio',
  // 'Islamic Architecture',
  // 'Tigers',
  // 'National Historic Landmark',
  // "Assassin's Creed",
  // 'Gathering Place',
  // 'Expensive',
  // 'Ferry',
  // 'Mies van der Rohe',
  // 'Mill',
  // 'Geological Site',
  // 'Fritz Höger',
  // 'Jazz',
  // 'Accessories',
  // 'Fauna',
  // 'Presidential Residence',
  // 'Drinks',
  'Flower Garden',
  // 'Tasting',
  // 'Berlin State Museum',
  // 'Islamic Art',
  // 'Ride',
  // 'Italian Renaissance Architecture',
  // 'Marcel Duchamp',
  // 'Fabergé Egg',
  // 'Paul Gauguin',
  // 'Anthony van Dyck',
  // 'Motte-and-bailey Castle',
  // 'Animal Sanctuary',
  // 'River Baths',
  // 'Landzeit',
  // 'Movie & TV Tour',
  // 'Romantic',
  // 'Macaron',
  // 'Religious Art',
  // 'Model',
  // 'Medical Museum',
  // 'Neo-Futurist Architecture',
  // 'Ancient Egypt',
  // 'Turner',
  // 'Horse School',
  // 'Disney Park',
  // 'Crater',
  // 'Tribute',
  // 'Walt Disney',
  // 'Arboretum',
  // 'Gustav Klimt',
  // 'Catacombs',
  // 'Disco Club',
  // 'Cross',
  // 'Tourist Street',
  // 'Housing Complex',
  // 'Stock Exchange',
  // 'Courtyard',
  // 'Futurist Architecture',
  // 'Carvings',
  // 'Arcade Games',
  // 'Sand Dunes',
  // 'Jean Metzinger',
  // 'Jasper Johns',
  // 'Auguste Rodin',
  // 'Stone Circle',
  // 'Dominican',
  // 'Edwardian Architecture',
  // 'Ceramics Museum',
  // 'Cooking School',
  // 'Monedero Accepted',
  // 'Roadrunner Accepted',
  // 'Hospice',
  // 'Ice Bar',
  // 'Sacred Place',
  // 'Steak',
  // 'Geology Museum',
  // 'Altar',
  // 'Kayaking',
  // 'Forest Park',
  // 'Aviation Museum',
  // 'European Art',
  // 'Dinosaurs',
  // 'TV Tower',
  // 'Food Museum',
  // 'Crafts Market',
  // 'Ethnography',
  // 'Butterfly Park',
  // 'Sunbathing',
  // 'Cows',
  // 'Toulouse-Lautrec',
  // 'Bronze Age',
  // 'Augustinian',
  // 'Maya Site',
  // 'WWI',
  // 'Sailing School',
  // 'Water Level Monitoring',
  // 'Abandoned',
  // 'Beer Shop',
  // 'Gourmet Market',
  // 'IMAX',
  // 'Alley',
  // 'Museum of Architecture',
  // 'Indoor Arena',
  // 'Sport Museum',
  // 'National Library',
  // 'Mudéjar Architecture',
  // 'Beer Museum',
  // 'Dinosaur Museum',
  // 'Ethnic District',
  // 'Open-air',
  // 'Residential Area',
  // 'Media Museum',
  // 'Elephants',
  // 'Glass',
  // 'Bernini',
  // 'Ethnographic Museum',
  'Cat Café',
  // 'Arshile Gorky',
  // 'Rainforest',
  // 'Jan van Eyck',
  // 'Elizabethan Architecture',
  // 'Washington DC Explorer Pass',
  // 'Dresden City Card',
  // 'Rooftop Bar',
  // 'Romanesque Revival Architecture',
  // 'Universal Theme Park',
  // 'Very Expensive',
  // 'Frank Gehry',
  // 'Manga',
  // 'Lane',
  // 'Retro',
  // 'Catalan Cuisine',
  // '4D',
  // 'Equestrian',
  // 'Finance',
  // 'Illusion',
  // 'Aerial Tramway',
  // 'Lisbon City Card',
  // 'Disneyland',
  // 'Military Facility',
  // 'Calligraphy',
  // 'Judaism',
  // 'Underground',
  // 'Former Church',
  // 'Numismatic Museum',
  // 'Porcelain',
  // 'Camels',
  // 'Amedeo Modigliani',
  // 'Edvard Munch',
  // 'Kazimir Malevich',
  // 'Chinese Art',
  // 'Prehistoric Art',
  // 'African Art',
  // 'Henge',
  // 'Singaporean Cuisine',
  // 'Family Restaurant',
  // 'Tile Decoration',
  // 'Bohuslav Fuchs',
  // 'Floating Market',
  // 'Military Obstacle Course',
  // 'Methanol',
  // 'Cash Only',
  // 'Swahili Architecture',
  // 'Festival',
  // 'Lively',
  // 'Quarry',
  // 'Butterfly',
  // 'Historic Park',
  // 'Public Pool',
  // 'Astronomical Clock',
  // 'Sea World',
  // 'Sherlock Holmes',
  // 'Fjord',
  // 'Chocolatier',
  // 'James Bond',
  // 'Miniatures',
  // 'Road',
  // 'Gothic-Renaissance Architecture',
  // 'Panda',
  // 'Surrealism',
  // 'Immigration',
  // 'Heritage Centre',
  // 'Clothing Market',
  // 'Entertainment Resort',
  // 'Nazism',
  // 'Cloister',
  // 'San Francisco Explorer Pass',
  // 'Sunset-Watching',
  // 'Jewellery Museum',
  // 'Residential Complex',
  // 'Artificial Island',
  // 'Islam',
  // 'Abraham Lincoln',
  // 'Orchids',
  // 'Quick Bite',
  // 'Waterfalls System',
  // 'Neptune',
  // 'Medici',
  // 'Natural Springs',
  // 'Exercise Station',
  // 'Long Barrow',
  // 'Palladian Architecture',
  // 'Christopher Wren',
  // 'Bronze Sculpture',
  // 'Azulejos',
  // 'Meteora',
  // 'Spanish Colonial Architecture',
  // 'National Heritage',
  // 'New Objectivity Architecture',
  // 'Ale',
  // 'Orchestra',
  // 'Wharf',
  // 'Meal',
  // 'Education',
  // 'Business Center',
  // 'Cupcake',
  // 'Art Market',
  // 'Italian Art',
  // 'Dero',
  // 'Surgery',
  // 'Cultural Heritage',
  // 'Communism',
  // 'Middle Eastern Art',
  // 'Homemade',
  // 'National Theater',
  // 'River Island',
  // 'Confucian',
  // 'Hanok',
  // 'Hans Christian Andersen',
  // 'Ethnic Museum',
  // 'Traditional District',
  // 'Miniature Park',
  // 'Liquor Store',
  'Ceramic Art',
  // 'Grutt Pass',
  // 'Apartment House',
  // 'Cave System',
  // 'Roadside Attraction',
  // 'Lynxes',
  // 'Leopards',
  // 'Museum Ship',
  // 'Paleontology',
  // 'Mining Museum',
  // 'Plantation House',
  // 'Federal Architecture',
  // 'Richard Serra',
  // 'Cultural History',
  // 'Inca',
  // 'Pyramid',
  // 'Dravidian Architecture',
  // 'Koalas',
  // 'Australian Fauna',
  // 'Romantic Architecture ',
  // 'Red Light District',
  // 'Dušan Jurkovič',
  // 'Buddhist Art ',
  // 'Gordon Ramsay',
  // 'Penguin Colony',
  // 'SVO',
  'Mountain Lake',
  // 'Casual',
  // 'Ecological',
  'Brewpub',
  // 'Industry',
  // 'Hall',
  // 'Peninsula',
  // 'Hello Kitty',
  // 'Collectibles',
  // 'Cats',
  // 'Labyrinth',
  // 'Bread',
  // 'Cooking',
  // 'Thrift Shop',
  // 'Chain Bridge',
  // 'Chamber',
  // 'Jade',
  // 'Comics',
  // 'Games Area',
  // 'Sport Complex',
  // 'Silk',
  // 'Nine Eleven',
  // 'Rock Music',
  // 'Windsurfing',
  // 'Indoor Sporting Arena',
  // 'Specialty Shop',
  // 'National Stadium',
  // 'Cookies',
  // 'Currywurst',
  // 'City Tower',
  // 'Pop Art',
  // 'Commune',
  // 'Minaret',
  // 'Photo Booth',
  // 'Discount Shopping',
  // 'Native American',
  // 'Avant-garde',
  // 'Agricultural Museum',
  // 'Military Site',
  // 'Hardened Aircraft Shelter',
  // 'Artefacts',
  // 'Chinese Architecture',
  // 'Military Memorial',
  // 'Adventure Park',
  // 'Stalinist Architecture',
  // 'Road Bridge',
  // 'Holocaust Museum',
  // 'Prison Museum',
  // 'Egyptian',
  // 'František Kupka',
  // 'Frida Kahlo',
  // 'Oskar Kokoschka',
  // 'Dutch Art',
  // 'Rice Field',
  // 'Furniture Collection',
  // 'Whistler',
  // 'Medieval Village',
  // 'Bohemian',
  // 'English Baroque Architecture',
  // 'Michelangelo',
  // 'Visual Arts',
  // 'Rum',
  // 'Tudor Architecture',
  // 'Ghost Town',
  // 'Dance School',
  // 'Washing Machine',
  // 'SVG Accepted',
  // 'Rosenberger',
  // 'PDVSA',
  // 'Eclectic Cuisine',
  // 'Moderate Prices',
  // 'Perfume',
  // 'Whiskey',
  // 'Water Spring',
  // 'Sorbet',
  // 'Sign',
  // 'Ice Cave',
  // 'Bikeway',
  // 'LGBT',
  // 'David Černý',
  // 'Thermal',
  // 'Mining',
  'Gastropub',
  // 'Money',
  // 'Neo-Mudéjar Style',
  // 'Spanish Art',
  // 'Submarine',
  // 'Escalator',
  // 'African American',
  // 'Folk',
  // 'Jazz Bar',
  // 'The Beatles',
  // 'Herbs',
  // 'Artificial Beach',
  // 'Beach Club',
  // 'Dungeon',
  // 'East Germany',
  // 'S-Bahn',
  // 'Modern History',
  // 'Martin Luther King',
  // 'San Francisco CityPass',
  // 'Glass Museum',
  // 'Research Library',
  // 'Royal Family',
  // 'Singapore City Pass',
  // 'National Treasure',
  // 'Lobster',
  // 'Chinese Garden',
  // 'Cactus',
  // 'English Garden',
  // 'Naval History',
  // 'Printmaking',
  // 'Romano-Byzantine Architecture',
  // 'Malaysian Cuisine',
  // 'Applied Arts',
  // 'Open-air Theater',
  // 'Refugee Housing',
  // 'Churros',
  // 'Victory Monument',
  // 'Open-air Concert',
  // 'Military Cemetery',
  // 'Mineralogy Museum',
  // 'Social Life Hub',
  // 'Delicacies',
  // 'Film Archive',
  // 'Industrial Heritage Museum',
  // 'Coal Mine',
  // 'Educative',
  // 'Sandro Botticelli',
  // 'Musical Instruments',
  // 'Concentration Camp',
  // 'Roman Baths',
  // 'Carriage Museum',
  // 'Indoor Skiing',
  // 'Wine Museum',
  // 'Cistern',
  // 'Chinese Culture',
  // 'Tea Room',
  // 'Fossils',
  // 'Five Great Zen Temples',
  // 'Civil Architecture',
  // 'Hot Water Paid',
  // 'Comedy Club',
  // 'Lounge',
  // 'Power Plant',
  // 'Lava Cave',
  // 'John Lennon',
  // 'Miniature Railway',
  // 'Party Street',
  // 'Prayer',
  // 'Sundial',
  // 'Baptistery',
  // 'FC Barcelona',
  // 'Hollywood',
  // 'Replica',
  // 'Gold',
  // 'Veterans',
  // 'JFK',
  // 'Catalan Art',
  // 'English-style',
  // 'Trade Center',
  // 'Street Culture',
  // 'Multicultural',
  // 'Catalan Gothic',
  // 'Fairytales',
  // 'Dragon',
  // 'Jean Nouvel',
  // 'Cartoon Museum',
  // 'Seasonal Cuisine',
  // 'Modern Cuisine',
  // 'Air Force',
  // 'Space',
  // 'Arabic Bath',
  // 'Erotic Museum',
  // 'Salsa',
  // 'Hamburger',
  // 'Mesoamerican',
  'Textile Museum',
  // 'Anatomy',
  // 'Shipyard',
  // 'Manmade',
  // 'TV Studio',
  // 'Geisha Houses',
  // 'Deconstructivism',
  // 'Symbolism',
  // 'Home Alone',
  // 'Integrated Ticket of Palaces',
  // 'Visit Oslo Pass',
  // 'Military History',
  // 'Colonial History',
  // 'Cabaret Show',
  // 'Pokémon',
  // 'Thomas Jefferson',
  // 'Black Sand',
  // 'Burial Chamber',
  // 'Seals',
  // 'Church of Ireland',
  // 'Textile',
  // 'Guinness World Record',
  // 'Anthropological Museum',
  'Nonprofit',
  'Public Market',
  // 'Mint',
  // 'Water Castle',
  // 'Hippodrome',
  // 'Ossuary',
  // 'Cinema Museum',
  // 'Performing Arts',
  // 'Caldera Lake',
  // 'Caravaggio',
  // 'Australian Aboriginal',
  // 'Native American Art',
  // 'Roman Fort',
  // 'Iron Age',
  // 'Hillfort',
  // 'Keep',
  // 'Roman Villa',
  // 'Computer Repair Shop',
  // 'Organic Food',
  // 'Financial District ',
  // 'Banksy',
  // 'English Gothic Architecture',
  // 'Monolith',
  // 'Virtual Reality',
  // 'Treasury',
  // 'Ecotourism',
  // 'Medieval Art',
  // 'Italian Gothic Architecture',
  // 'Russian Architecture ',
  // 'Moneo Accepted',
  // 'Artificial Lake',
  // 'Viking Era',
  // 'Art Festival',
  // 'Sound Show',
  // 'Mexican Culture',
  // 'Stalagmite',
  // 'Etruscan Artefacts',
  // 'Educational Center',
  // 'Outlook',
  // 'Skansen',
  // 'Anne Frank',
  // 'LGBT Friendly',
  // 'Doctor Who',
  // 'Blue Flag',
  // 'Aviation',
  // 'Ropeway',
  // 'Burger Joint',
  // 'Coin Collection',
  // 'FC Köln',
  // 'Bundesliga',
  // 'Gardening',
  // 'Christmas',
  // 'Ecology',
  // 'Hippie Culture',
  // 'Multimedia',
  // 'DJ',
  // 'Oriental',
  // 'Day Spa',
  'City Garden',
  // 'Erotics',
  // 'Congress',
  // 'Film Screening',
  // 'Bike Parking',
  // 'U-Bahn',
  // 'Beach Bar',
  // 'Oscar Wilde',
  // 'Showroom',
  // 'Star Fortress',
  // 'Elevator',
  // 'Koreatown',
  // 'Glassware',
  // 'Joseon',
  // 'Champagne',
  // 'Belfry',
  // 'Edo',
  // 'Natural Science',
  // 'Traditional Items',
  // 'Computer Goods',
  // 'Cosplay',
  // 'Nordic Cuisine',
  // 'Fish Ladder',
  // 'Barracks',
  // 'Patisserie',
  // 'Ruin Pub',
  // 'Route 66',
  // 'Cheesecake',
  // 'Basalt Columns',
  // 'Peace Museum',
  // 'Greco-Roman Mythology',
  // 'Double-deck Bridge',
  // 'Indigenous',
  // 'Bees',
  // 'Rooftop',
  // 'Lord of the Rings',
  // 'Haunted House',
  // 'Canadian Art',
  // 'Egon Schiele',
  // 'Diego Rivera',
  // 'Korean Art',
  // 'Australian Art',
  // 'Scottish History',
  // 'Mona Lisa',
  'Bath House',
  // 'Menhir',
  // 'Burial Mound',
  // 'Hermitage',
  // 'Irish History',
  // 'Hawker Centre',
  // 'Luge',
  // 'Custom House',
  // 'Greek Art',
  // 'Botanic Museum',
  // 'Mozart',
  // 'National Register of Historic Places',
  // 'Design Market',
  // 'Wet Market',
  // 'Barack Obama',
  // 'Russian Revival Architecture',
  // 'Cirque du Soleil',
  // 'Film Festival',
  // 'Medieval Underground',
  // 'Discovery Museum',
  // 'Sequoia Tree',
  // 'Ernest Hemingway',
  // 'Cenote',
  // 'Road Junction',
  // 'Dinosaur Park',
  // 'Funny',
  // 'Dolls',
  // 'Utensils',
  // 'Cinematography',
  // 'Icelandic Cuisine',
  // 'Cubism',
  // 'Grilled Fish',
  // 'Symphony',
  'Minimalism',
  // 'Food Festival',
  // 'Ecosystem',
  // 'Fishermen',
  // 'American Indian',
  // 'Sex',
  // 'Liberty',
  // 'Home Decor',
  // 'Merchandise',
  // 'Catalan History',
  // 'Templars',
  // 'Gin',
  // 'Diamonds',
  // 'Skyline',
  // 'Coca-Cola',
  // 'Road Sign',
  // 'Roman Empire Theme',
  'Espresso',
  // 'Spire',
  // 'Manueline Architecture',
  // 'Byzantine Museum',
  // 'Vietnam War',
  // 'Development Project',
  // 'Mythical',
  // 'Five Grand Palaces',
  // 'Cellars',
  // 'Kimchi',
  // 'Korean Restaurant',
  // 'Driving Experience',
  // 'Robot',
  // 'Clock Museum',
  // 'Advertising Museum',
  // 'Deer Park',
  'Mountain Resort',
  // 'Absinthe',
  // 'Research Institution',
  // 'Brewery Headquarters',
  // 'Mythology',
  // 'Skydiving',
  // 'Sea Cavern',
  // 'Whale Watching',
  // 'Heritage Railroad',
  // 'Swing Bridge',
  // 'Rococo',
  // 'Allegorical Sculpture',
  'Techno Club',
  // 'Manuscript',
  // 'Tea Plantation',
  // 'Galileo',
  // 'Dante Alighieri',
  // 'Costumes',
  // 'Yachting',
  // 'Hobbit',
  // 'Arab Culture',
  // 'Middle Ages',
  'State Natural Area',
  // 'Alphonse Mucha',
  // 'James Turrell',
  // 'No Permanent Exhibition',
  // 'Oceanian Art',
  // 'Turret',
  // 'Celtic',
  // 'Anglo-Saxon',
  // 'Chambered Tomb',
  // 'Irish Whiskey',
  // 'Gatehouse',
  // 'Chalk',
  'Lava Fields',
  'Salt Ponds',
  // 'Border',
  // 'Amusement Center',
  // 'Deities',
  // 'Asian Culture',
  // 'Masonic Museum',
  'Irish Pub',
  // 'Tea Museum',
  // 'Downton Abbey',
  // 'Souk',
  // 'Egyptian Art',
  // 'Greek Gods',
  // 'Administrative Building',
  // 'George Washington',
  // 'Malay Culture',
  // 'Canopy Walkway',
  // 'Police Museum',
  // 'Former Hospital',
  // 'Ice Hotel',
  // 'Presidential Museum',
  'Deep Dish Pizza',
  // 'Important Cultural Property',
  // '3D',
  // 'Folk Museum',
  // 'Edo Period Architecture',
  // 'Late Gothic Architecture',
  // 'Moated Castle',
  // 'Salt Mine',
  // 'Tortoise',
  // 'Maori',
  'Volcanic Area',
  // 'Byzantine Revival Architecture',
  // 'Amsterdam School Architecture',
  // 'Flower Farm',
  // 'Plateresque Architecture',
  // 'Books',
  // 'Cultural Festival',
  // 'Contemporary Cuisine',
  // 'Stone Arch',
  // 'Brand',
  // 'Backlot',
  // 'Ernst Wiesner',
  // 'Adolf Loos',
  // 'Recording Studio',
  // 'Franz Kafka',
  // 'Padlock',
  // 'Lace',
  // 'Original',
  // 'Habsburg',
  // 'Theme Bar',
  // 'Chiang Kai-shek',
  // 'Creative Park',
  // 'Rocket Station',
  // "M&M's",
  // 'Alice in Wonderland',
  // 'Lavender',
  // 'Les Miserables',
  // 'Jan Neruda',
  // 'Amélie',
  // 'D-Day',
  // 'Dairy-Free',
  // 'Gun Firing',
  // 'Oratory',
  // 'Columbus',
  // 'Great Wall',
  // 'Fair Trade',
  // 'Mirror Maze',
  // 'Drive',
  // 'Cartoons',
  // 'Tournament',
  // 'Experiments',
  // 'Toasts',
  // 'Herb Shop',
  // 'Roman Temple',
  // 'Botany',
  // 'Pre-Columbian Art',
  // 'Abstract Art',
  // 'Bangkok City Pass',
  // 'Portuguese Heritage',
  // 'Classical Music',
  // 'Torture Museum',
  // 'Oriental Art',
  // 'Stasi',
  // 'Ritter Sport',
  // 'Hipster',
  // 'Girl',
  // 'Stalactite',
  // 'David Hume',
  // 'Venetian Glass',
  // 'Wishing Well',
  // 'Friends',
  // 'Blues',
  // 'Cappuccino',
  // 'Crossing',
  // 'Literary Events',
  // 'Electronic Dance',
  // 'Space Center',
  // 'Roof',
  // 'French',
  // 'Cannabis Museum',
  // 'Counterculture',
  // 'Cannabis Culture',
  // 'Anarchism',
  // 'Milan Pass',
  // 'Melbourne Attractions Pass',
  // 'Korean War',
  // 'Joseon Architecture',
  // 'Traditional Theater',
  // 'Oriental Medicine',
  // 'World Cup',
  // 'Albert Einstein',
  // 'Truffles',
  // 'Pines',
  'Ninja',
  'Structural Expressionism',
  // 'Maid Café',
  // 'Tennis Court',
  // 'State Guesthouse',
  // 'Choir',
  // 'Candy Factory',
  // 'Auction House',
  // 'Loch Ness',
  // 'Titanic',
  // 'Plane Wreck',
  // 'Crown Jewels',
  // 'Knitting',
  // 'Railway Terminal',
  // 'Eiffel Company',
  // 'Medicinal Bath',
  // 'Fairground',
  // 'Nighttime show',
  // 'Textile Shop',
  // 'Theme Hotel',
  // 'Capitol',
  'Natural Bridge',
  // 'Cartoon Character',
  // 'Video Sculpture',
  // 'Berlin City Pass',
  // 'Olympic Stadium',
  // 'Karl Marx',
  // 'Martin Luther',
  // 'Shell Museum',
  // 'Antique',
  // 'Vertical Garden',
  // 'Cosmetics',
  // 'Hummus',
  // 'Machiavelli',
  // 'Amannati',
  // 'Rafting',
  // 'Reptiles',
  // 'Tramway Museum',
  // 'Colonial Revival',
  // 'Hermitage Museum',
  // 'Mill Museum',
  // 'Hacienda',
  // 'Bird Show',
  // 'James Joyce',
  // 'Alfred Stieglitz',
  // 'Clyfford Still',
  // 'Muslim Art',
  // 'Swiss Art',
  // 'Water Complex',
  // '19th Century Art',
  'Russian Art',
  'British Art',
  // 'William Blake',
  // 'Canadian History',
  'Indian Art',
  // 'Whisky',
  // 'Milecastle',
  // 'Fishery',
  // 'Plague',
  // 'Crystal',
  // 'Marine Art',
  // 'Amusement Museum',
  // 'Peranakan Culture',
  // 'Immigration Museum',
  // 'Condo',
  // 'Communication Museum',
  // 'Roman Athens',
  // 'Gold Mine',
  // 'Bat Cave',
  // 'Rebel Without a Cause',
  // 'La La Land',
  // 'Caldera',
  // 'Berber Culture',
  // 'Princess Diana',
  // 'Andrea Palladio',
  // 'Steamed Dumplings',
  // 'Conservation Centre',
  // 'SEA LIFE',
  // 'Outdoor Cinema',
  // 'Spy Museum',
  // 'Spanish Revival Architecture',
  // 'Parkway',
  // 'Pinball Museum',
  // 'Second Empire Architecture',
  // 'Warehouse District',
  // 'Salt Lake',
  // 'Brazilian Culture',
  // 'Moraine',
  // 'Salt Flat',
  // 'Whaling Museum',
  // 'Avant Accepted',
  'National Historic Site',
  // 'Omani Architecture',
  // 'British Colonial Architecture',
  // 'Marine Reserve',
  // 'Steel Sculpture',
  'Land Art',
  'Mountain Biking',
  // 'Historic District',
  // 'Music Festival',
  // 'Therapy',
  // 'Grand Slam',
  // 'Marie Curie',
  // 'Forrest Gump',
  // 'Animation Studio',
  // 'Reformation',
  // 'Nuclear Research',
  // 'Parade',
  // 'Royal Guards',
  'Game Preserve',
  // 'Fryderyk Chopin',
  // 'Notting Hill',
  // 'Peter Pan',
  // 'Promontory',
  // 'Fantasy',
  // 'Lanterns',
  // 'Magic',
  // 'Flying',
  // 'The Exorcist',
  // 'Taiwan High Speed Rail',
  // 'Oscars',
  // 'Academy Awards',
  // 'Ghostbusters',
  // 'Tortilla',
  // 'Mezcal',
  // 'Tapería',
  // 'Point Zero',
  // 'Hamleys',
  // 'Gondola',
  // 'T-Shirts',
  // 'Politics',
  // 'Ladyboys',
  // 'Fortune Cookies',
  // 'Goldfish',
  // 'Grand Prix',
  // 'Motorcycle Circuit',
  // 'Foot Guards',
  // 'Roman Cuisine',
  // 'Industrial Complex',
  // 'Subway',
  // 'Tea Ware',
  // 'Funeral Carriages',
  // 'Teaching Center',
  // 'Congee',
  // 'Beach Football',
  // 'Olympic Museum',
  // 'Erotic Art',
  // 'Residential Block',
  // 'Latin Music',
  // 'Ham',
  // 'Jamón',
  // 'Institutional Building',
  // 'Tiramisu',
  // 'Former Synagogue',
  // 'Crocodile Zoo',
  // 'Snake Farm',
  // 'Pastrami',
  // 'Jamie Oliver',
  // 'Microbes',
  // 'Red Army',
  // 'Christiane F.',
  // 'We Children from Bahnhof Zoo',
  // 'Computer Games',
  // 'Iron Curtain',
  // 'Boatyard',
  // 'Early History Collections',
  // 'Playboy',
  // 'Celebrity Home',
  // 'Talk Show',
  // 'Prussian Cuisine',
  // 'Nefertiti',
  // 'House Sign',
  // 'Louis Vuitton',
  // 'Canvas Painting',
  // 'Metronome',
  // 'Mathematics',
  // 'Lightship',
  // 'Earth',
  // 'Sex and the City',
  // 'Lion King',
  // 'Punk',
  // 'Speakeasy',
  // 'Mermaid',
  // 'Sun Temple',
  // 'Presidential Office',
  // 'Istanbul Tourist Pass',
  // 'Summit',
  // 'Floating Village',
  // 'Jjimjilbang',
  // 'Broadcasting',
  // 'Media',
  // 'Female University',
  // 'The Eight Gates of Seoul',
  // 'Puppy Cafe',
  // 'Pets',
  // 'Imperial Shrine',
  // 'Dutch Architecture',
  // 'Jungfrau Travel Pass',
  // 'Succulent',
  // 'Indoor Theme Park',
  // 'French Garden',
  // 'Kabuki',
  // 'Ghibli',
  // 'Miyazaki',
  // 'Japanese Sword',
  // 'Extravagant',
  // 'Cheese Factory',
  // 'Gadgets',
  // 'Azalea',
  // 'Assassination Site',
  // 'Franklin Delano Roosevelt',
  // 'Game Simulators',
  // 'FBI',
  // 'Historic Scotland',
  // 'Richelieu',
  // 'Silver',
  // 'Snow Park',
  // 'Tuscan Cuisine',
  // 'Modern French Cuisine',
  // 'Christian Art',
  // 'Music Conservatory',
  // 'Fascism',
  // 'Spirits',
  // 'Stalagmite Formations',
  // 'Observation Tunnel',
  // 'Museum Village',
  // 'Modern British Cuisine',
  // 'Bicycle Repair Station',
  'Tide Pool',
  // 'Shield Volcano',
  'Van Gogh Museum',
  // 'Fireworks',
  // 'Believe It or Not',
  // 'Corridor',
  'Olive Oil Farm',
  // 'Fishing Port',
  // 'Pebble Beach',
  // 'Late Victorian',
  // 'Anthropology',
  // 'Creole Cuisine',
  // 'Edgar Allan Poe',
  // 'Holocaust Commemoration',
  'Sports Stadium',
  // 'Nazi Architecture',
  // 'Artificial Hill',
  // 'Dog Sledding',
  // 'Tudor Revival Architecture',
  // 'Burlesque',
  // 'Cocoa',
  // 'Belle Epoque',
  // 'Controversial',
  // 'Skull',
  // 'Former Mosque',
  // 'Roman Theater',
  // 'Botticelli',
  // 'Swiss Chalet',
  // 'Sephardic Synagogue',
  'Art Society',
  'State Capitol',
  // 'Book Museum',
  // 'Tequila',
  // 'Hat Shop',
  // 'Khmer Cuisine',
  // 'Great Moravia',
  // 'Doll Museum',
  'National Recreation Area',
  // 'Soufflé',
  // 'American Gothic',
  // 'Poster Collection',
  // 'Ansel Adams',
  // 'Yoko Ono',
  // 'Adolph Gottlieb',
  // 'Richard Hamilton',
  // 'Olafur Eliasson',
  // 'Socialist Realism',
  // 'Marina Abramović',
  // 'Exotic',
  // 'Balinese Cuisine',
  // '18th Century Art',
  // "Foucault's Pendulum",
  // 'Celtic Art',
  // 'Dolly the Sheep',
  // 'Colonial Art',
  // "Michelangelo's David",
  // 'Russian Icons',
  // 'Israeli Art',
  // 'Paolo Uccello',
  // 'Nefertiti Bust',
  'Irish Art',
  // 'Fogou',
  // 'Ringwork',
  // 'Military Architecture',
  // 'Standing Cross',
  // 'Folly',
  // 'Water Conduit',
  // 'Hill Figure',
  // 'Battle of Worcester',
  // 'Cast Iron',
  // 'Fish House',
  // 'Packhorse Bridge',
  // 'Jacobean Architecture',
  // 'Double Monastery',
  // 'Blue Plaque',
  // 'Sinking River',
  // 'Jan Skácel',
  // 'Manchester United',
  // 'Underground River',
  // 'Television Studio',
  // 'Silver Mine',
  // 'Royal Monument',
  // 'Floral Clock',
  // 'Tempura',
  // 'Market Town',
  // 'Grimm Brothers',
  // 'Hellenistic Architecture',
  // 'New Spanish Baroque Architecture',
  // 'Greek Yogurt',
  // 'Water Pipe',
  // 'Lope de Vega',
  // 'Spanish Culture',
  // ' Gustave Eiffel',
  // 'Tannery',
  // 'Puppet Museum',
  // 'Mamluk Architecture',
  // 'Maurizio Cattelan',
  // 'Alexander Hamilton',
  // 'Car Factory',
  // 'Phallic Architecture',
  // 'Indo-Saracenic Architecture',
  // 'Freedom Trail',
  // 'Armenian Architecture',
  // 'Trick Eye Museum',
  // 'Teddy Bears',
  // 'Immersive Gallery',
  // 'Musical Group',
  // 'Afro-Brazilian Culture',
  // 'Percussion Ensemble',
  // 'Telecommunications Museum',
  // 'Plaque',
  // 'Body Worlds',
  // 'Tank Ride',
  // "Women's Museum",
  // 'Sky Walk',
  // 'Self-guided Tour',
  // 'Spanish Colonial Revival Architecture',
  // 'Emigration Museum',
  // 'Palace Gate',
  // 'Bell Shop',
  // 'Ludwig van Beethoven',
  // 'Wiel Arets Architects',
  // 'Fault',
  // 'Lava Flow',
  // 'Fumarole',
  // 'Mud Volcano',
  // 'Parrots',
  // 'Steampunk',
  // 'Lava Tube',
  // 'Empire Style',
  // 'Ramon Casas',
  // 'Snakes',
  // 'Coffee Farm',
  // 'Coral Reefs',
  // 'Grotto',
  // 'American West ',
  // 'Medieval Architecture',
  // 'Minor Basilica',
  // 'Cargo terminal',
  // 'Passenger Terminal',
  // 'Night Cruise',
  // 'Sporting Event & Package',
  // 'River Rafting & Tubing',
  // 'Entertainment Cruise',
  // 'Readings/Lectures',
  // 'Quiet',
  // 'Napoleon III',
  // 'Bell',
  // 'Puffin',
  // 'Rem Koolhaas',
  // 'Basque',
  // 'Jim Morrison',
  // 'Etruscan Town',
  // 'Twilight',
  // 'Royal Symbol',
  // 'Park Railway',
  // 'Filtering Station',
  // 'Cruiser',
  // 'Offroad',
  // 'Sci-fi',
  // 'Pineapple Cake',
  // 'Joël Robuchon',
  // 'Belvedere',
  // 'Boots',
  // 'Northern Lights',
  // 'Geothermal Power Plant',
  // 'Leather Goods Store',
  // 'Ministry of Foreign Affairs',
  // 'Skeletons',
  // 'Former Racing Circuit',
  // 'Kite Flying',
  // 'Taiwanese Culture',
  // 'Masia',
  // 'Raw',
  // 'Multiplex',
  // 'Police Box',
  // 'Black Madonna',
  // 'Infant Jesus',
  // 'Josef Gočár',
  // 'Jan Palach',
  // 'Medal',
  // 'Order',
  // 'Legion of Honor',
  // 'Flag Raising Ceremony',
  // 'Gustav Mahler',
  // 'Brick Arch',
  // 'Anglophone Art',
  // 'Brass Rubbing',
  // 'Sex Shop',
  // 'YouTube',
  // 'Star Wars',
  // 'Gun Battery',
  // 'Cosmetic Treatments',
  // 'Historical Garden',
  // 'Pizza Hut',
  // 'Rave',
  // 'Poe',
  // 'Cog Railway',
  // 'Religious School',
  // 'Music Collection',
  // 'Quiche',
  // 'Feng Shui',
  // 'Academia',
  // 'Figurative Art',
  // 'Google Art Project',
  // 'Gazpacho',
  // 'Madrilla Restaurant',
  // 'Sorolla',
  // 'IT Shopping Mall',
  // 'Barges',
  // 'Wave Pool',
  // 'Sir Walter Scott',
  // 'Condoms',
  // 'Wurst',
  // 'Helmut Newton',
  // 'Revue',
  // 'Nintendo',
  // 'Game',
  // 'Chorus Pass',
  // 'Scientology',
  // 'Scientology Center',
  // 'Black Books',
  // 'News Agency',
  // 'Flemish Cuisine',
  // 'Beer Spa',
  // 'Bust',
  // 'Theodore Roosevelt',
  // 'Quiet Zone',
  // 'Rare',
  // 'Aladdin',
  // 'European Parliamant',
  // 'Sydney Pass',
  // 'Korean Theater',
  // 'General Wholesale',
  // 'Orangutans',
  // 'Rock Reliefs',
  // 'Cambodian Culture',
  // 'Sejong',
  // 'Theatre Complex',
  // 'Bronze Bell',
  // 'Korean Re-enactment',
  // 'KBS',
  // 'Korean Chicken Soup',
  // 'Experience Program',
  // 'Sumo',
  // 'DMZ',
  // 'Diplomatic Site',
  // 'Portal',
  // 'Celtic Christianity',
  // 'Western Art',
  // 'Shingon',
  // 'Aikido',
  // 'Gundam',
  // 'Freddie Mercury',
  // 'Dublin Freedom Pass',
  // 'York Pass',
  // 'Medieval Pass',
  // 'Pudding',
  // 'Herbarium',
  // 'Purikura',
  // 'East Asian Art',
  // 'Apparel',
  // 'Lifestyle',
  // 'Japanese Metabolism Movement',
  // 'Olympic Village',
  // 'Antonio Vivaldi',
  // 'South American Cuisine',
  // 'Korean Barbecue',
  // 'Sri Lankan Cuisine',
  // 'Giacomo Casanova',
  // 'Geopark',
  // 'Palma Pass',
  // 'Horse Show',
  // 'Salamanca Card',
  // 'Venetian Mask',
  // 'Mask',
  // 'Sewer',
  // 'Imre Varga',
  // 'Hourglass',
  // 'Scottish Cuisine',
  // 'Jungle',
  // 'Four Seasons Hotels',
  // 'Duty-Free',
  // 'Modern Asian Cuisine',
  // 'Jane Austen',
  // 'Shave Ice',
  // 'Disney Vacation Club',
  'Human Rights',
  // 'Orangery',
  // 'Experimental Musical Instrument',
  // 'Novelty Architecture',
  // 'Water Polo',
  // 'Ottoman Cuisine',
  // 'River Bend',
  // 'Aircraft Carrier',
  'Pawn Shop',
  // 'Facebook',
  // 'Thermometer',
  // 'Vitrage',
  // 'Rocket',
  // 'Pie Cart',
  // 'Spirit Wall',
  // 'Execution Site',
  // 'Gay Village',
  // 'Computer Museum',
  // 'Donkey',
  // 'Solar Telescope',
  // 'Sexuality',
  // 'Merit',
  // 'Palestine',
  // 'A.C. Milan',
  // 'Crocodile',
  // 'Bone',
  // 'Last Supper',
  // 'Brunelleschi',
  // 'Mallorcan Cuisine',
  // 'Condom Shop',
  // 'Skinny House',
  'Cat Museum',
  // 'Davizzi',
  // 'Tropical Culture',
  // 'Dutch Golden Age',
  // 'Fluorescent Art',
  // 'Punk Rock',
  // 'Former Lake',
  // 'Canal House',
  // 'Dutch Classicism',
  // 'Porcelain Factory',
  // 'Cattle',
  // 'Coal Camp',
  // 'Military Chapel',
  // 'Quilt Museum',
  // 'Thomas Edison',
  // 'Sandstone Cave',
  // 'Cotton Museum',
  // 'Farm Museum',
  // 'Basketball Museum',
  // 'Italianate Architecture',
  'Rock Climbing Gym',
  // 'Boutique Hotel',
  // 'Royal Villa',
  // 'Space History',
  // 'Hispanic Culture',
  'Popular Arts',
  // 'Habitat',
  // 'Tarsila do Amaral',
  // 'Candido Portinari',
  // 'Ismael Nery',
  // 'Anita Malfatti',
  // 'Pietro Marussig',
  // 'Tom Thomson',
  // 'Grant Wood',
  // 'Georges Braque',
  // 'Henri Michaux',
  // 'Paula Modersohn-Becker',
  // 'Slovenian Art',
  // 'Ukiyo-e',
  // 'Mexican Art',
  // 'Arnulf Rainer',
  // 'Oldest Hockey Stick',
  // 'Korean History',
  // 'Arms',
  // 'Armour',
  // 'British History',
  // 'Industrial Revolution',
  // 'Austrian Art',
  // "Klimt's Kiss",
  // 'Stradivarius',
  // "Guy Fawkes' Lantern",
  // 'Turkish Art',
  // 'Video Art',
  // 'Furnace',
  // 'Battle of Hastings',
  // 'Disk Barrow',
  // 'Bowl Barrow',
  // 'Prodigy House',
  // 'Japanese Whisky',
  // 'Entrance Grave',
  // 'Ramparts',
  // 'Roman-Saxon',
  // 'Preserved',
  // 'Oak',
  // 'Battle of Lansdowne',
  // 'Cluniac',
  // 'Robin Hood',
  // "Merchant's House",
  // 'Tithe Barn',
  // 'Causewayed Enclosure',
  // 'Timber Circle',
  // 'Bird Market',
  // 'Traffic Park',
  // 'Street Circuit',
  // 'Monaco Grand Prix',
  // 'Leoš Janáček',
  // 'Firehouse',
  // 'Apartheid',
  // 'Stoa',
  // 'Hindu Community',
  // 'Township',
  // 'Causeway',
  // 'Table Hockey',
  // 'Painted Windows',
  // 'Tennis Museum',
  // 'Ferrari',
  // 'Gulf',
  // 'Academic Gothic Architecture',
  // 'Parasite Museum',
  // 'Fetish Clothes',
  // 'Steve Jobs',
  // 'Machine',
  // 'Water Palace',
  // 'Cycladic Art',
  // 'Nobel Prize',
  // 'Waterway',
  // 'Bulgarian Orthodox',
  // 'Pathology',
  // 'Travertines',
  // 'Warner Bros',
  // 'Illustrations',
  // 'Portuguese Art',
  // 'Port Wine',
  // 'Dolmen',
  // 'Traditional Dance',
  // 'Josef Polášek',
  // 'František Kalivoda',
  // 'Arnošt Wiesner',
  // 'Fatimid Architecture',
  // 'Coptic Orthodox Church',
  // 'Dan Brown',
  // 'Philatelic Museum',
  // 'Neo-Palladian Architecture',
  // 'James Cook',
  // 'St. Patrick',
  // 'Private Beach',
  // 'Lapidary Museum',
  // 'Rosarium',
  // 'Wholesale Market ',
  // 'Hare Krishna',
  // 'M. C. Escher',
  // 'Industrial Architecture',
  // 'Coral Sea',
  // 'Aloe Vera',
  // 'Danish Art',
  // 'Omri Amrany',
  // 'Frederick Douglass',
  // 'George Mason',
  // 'Roastery',
  // 'Prague Welcome Card',
  // 'Ming Dynasty Architecture',
  // 'Pinball',
  // 'Lily Pool',
  // 'Civic Center',
  // 'Op art',
  // 'Memorial House',
  // 'Green Architecture',
  // 'Yutaro Noguchi',
  'Reflecting Pool',
  // 'Brick Gothic',
  // 'Brick Expressionism',
  // 'Paternoster',
  // 'Käthe Kollwitz',
  // 'Expressionism',
  // 'CityTourCard',
  // 'Mustard Shop',
  // 'Roy Lichtenstein',
  // 'Eternal Flame',
  // 'Green Roof',
  // 'Rinzai Zen Buddhism',
  // 'Human Evolution',
  // 'Johann Sebastian Bach',
  // 'Jorge Amado ',
  // 'African Culture',
  // 'Desert Safari',
  // 'Rogelio Salmona',
  // 'Javier Senosiain',
  // 'Organic Architecture ',
  // 'Cloud Forest',
  // 'Toilet Museum',
  // '400V',
  // 'Pakistan State Oil',
  // 'French Gothic Architecture',
  // 'Horological Museum',
  // 'River Terrace',
  // 'Ukrainian Baroque',
  // 'Byzantine Art',
  // 'Tinker',
  // 'Dugald Stewart',
  // 'Galileo Galilei',
  // 'Secondhand Bookshop',
  // 'Indian Architecture',
  // 'Capsule Architecture',
  // 'Extreme Piste',
  // 'Pediatrist',
  // 'Egyptian Architecture',
  // 'Eduardo Catalano',
  // 'Flag',
  // 'Spanish Civil War',
  // 'Naturist',
  // 'W. B. Yeats',
  // 'Plane Spotting',
  // 'Sacrificial Stone',
  // 'Cold-storage plant',
  // 'Douglas Fir',
  // 'Roman Road',
  // 'Tanker Terminal',
  // 'Container Terminal',
  // 'Vehicle Terminal',
  // '',
];
export const myTags = tags;
